### PR TITLE
Profiling support

### PR DESCRIPTION
**Pull request by marcelofg55**
This can be added now that https://github.com/godotengine/godot/pull/21229 was merged.

Note: To make functions send profiling data to godot use `GODOT_PROFILING_FUNCTION` (`DEBUG_ENABLED` must be declared on the SConstruct) on each function, like this:

```
void Player::TestFunctions() {
    GODOT_PROFILING_FUNCTION

    // actual code after GODOT_PROFILING_FUNCTION
}
```

### CODE REVIEW

**Comment by karroffel** [comment]
This needs to be updated to reflect the name changes done in the Godot side, then it should be good to go :)

**Comment by marcelofg55** [comment]
> This needs to be updated to reflect the name changes done in the Godot side, then it should be good to go :)

I've realized this needs NativeScript 1.1 now, after I moved the `godot_nativescript_profiling_add_data` function its now part of `godot_gdnative_ext_nativescript_1_1_api_struct`. So I'll wait for the NativeScript 1.1 to be merged to master.

**Comment by BastiaanOlij** [comment]
@marcelofg55 nativescript 1.1 has been merged, can you check if this is still valid and if so update the PR?

**Comment by marcelofg55** [comment]
@BastiaanOlij I have a question regarding nativescript 1.1, hope it's okay if I ask it here. I'm converting my code to nativescript 1.1 and I used to have this code:

```
	Node *area = (Node*)(Object*)loader->call("getAreaScript");
//	Node *area = (Node*)(godot_object*)loader->call("getAreaScript"); // this compiles on 1.1 but crashes later on ->call
	if (area) {
		if (area->call("isDisableMiniMap")) {
			attenuate = false;
		}
	}
```
`getAreaScript` is a GDScript function that returns a Node basically, it worked fine in nativescript 1.0 but now its crashing when I execute a call on area. What's the right way of doing this now with 1.1?

**Comment by BastiaanOlij** [comment]
@marcelofg55 not sure, my gut feeling says:
```
Ref<Node> area = loader->call("getAreaScript");
if (area.is_valid()) {
  if (area->call("isDisableMiniMap")) {
    attenuate = false;
  }
}
```
Might work, but I could be very wrong.

**Comment by marcelofg55** [comment]
Your suggestion makes sense but its failing to compile:
```
gcc-5 -o src/sample_player.os -c -fPIC -g -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wno-unused-but-set-parameter -m64 -O0 -DDEBUG_ENABLED -fPIC -I. -Isrc -Iinclude -Igodot-cpp/godot_headers -Igodot-cpp/include -Igodot-cpp/include/core -Igodot-cpp/include/gen src/sample_player.cpp
In file included from godot-cpp/include/core/Godot.hpp:13:0,
                 from include/common.h:7,
                 from include/sample_player.h:4,
                 from src/sample_player.cpp:1:
godot-cpp/include/core/Ref.hpp: In instantiation of 'void godot::Ref<T>::unref() [with T = godot::Node]':
godot-cpp/include/core/Ref.hpp:161:9:   required from 'godot::Ref<T>::Ref(const godot::Variant&) [with T = godot::Node]'
src/sample_player.cpp:50:47:   required from here
godot-cpp/include/core/Ref.hpp:180:17: error: 'class godot::Node' has no member named 'unreference'
   if (reference && reference->unreference()) {
                 ^
godot-cpp/include/core/Ref.hpp: In instantiation of 'void godot::Ref<T>::ref(const godot::Ref<T>&) [with T = godot::Node]':
godot-cpp/include/core/Ref.hpp:168:6:   required from 'godot::Ref<T>::Ref(const godot::Variant&) [with T = godot::Node]'
src/sample_player.cpp:50:47:   required from here
godot-cpp/include/core/Ref.hpp:26:4: error: 'class godot::Node' has no member named 'reference'
    reference->reference();
    ^
scons: *** [src/sample_player.os] Error 1

```

**Comment by marcelofg55** [comment]
This is ready for review/merge.

**Comment by marcelofg55** [comment]
@BastiaanOlij I've just fixed the nativescript_terminate thing on the PR and rebased it to the latest master. I guess the PR should be okay now.

**Comment by BastiaanOlij** [comment]
@marcelofg55 it's still showing that it wants to remove the nativescript_terminate method though?

**Comment by marcelofg55** [comment]
@BastiaanOlij Just re-fixed that, seems fine now :)
