### ISSUE TITLE
Can not compile bindings on linux

### ISSUE THREAD

**Issue by Homerus25** [GodotNativeTools/godot-cpp#392]
as the [documentation](https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html) says I cloned the repository and build the api.json with godot. godot was compiled with the latest updates on the master branch in 64bit mode. But I get an error when compiling:
```
scons platform=linux generate-bindings=yes use_custom_api_file=yes custom_api_file=../api.json bits=64 -j4
```
output:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/core/Basis.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Basis.cpp
g++ -o src/core/TagDB.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/TagDB.cpp
g++ -o src/core/Dictionary.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Dictionary.cpp
g++ -o src/core/NodePath.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/NodePath.cpp
g++ -o src/core/RID.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/RID.cpp
g++ -o src/core/GodotGlobal.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/GodotGlobal.cpp
g++ -o src/core/Vector3.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Vector3.cpp
g++ -o src/core/Transform.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Transform.cpp
g++ -o src/core/AABB.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/AABB.cpp
g++ -o src/core/Transform2D.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Transform2D.cpp
g++ -o src/core/Array.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Array.cpp
g++ -o src/core/Vector2.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Vector2.cpp
g++ -o src/core/Plane.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Plane.cpp
g++ -o src/core/PoolArrays.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/PoolArrays.cpp
g++ -o src/core/Variant.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Variant.cpp
src/core/Variant.cpp:8:10: fatal error: Object.hpp: No such file or directory
    8 | #include "Object.hpp"
      |          ^~~~~~~~~~~~
compilation terminated.
scons: *** [src/core/Variant.o] Error 1
scons: building terminated because of errors.
```
I am on Manjaro linux 64 bit, g++ version 9.3.0
Any suggestions what I can do?

**Comment by sheepandshepherd** [comment]
`generate_bindings` with an underscore. Did it create files in `include/gen/` and `src/gen/`?

GDNative doesn't work with master (4.0) branch yet. It'll be a few months before all the breaking API changes are integrated in godot-cpp. Use the 3.2 branch

**Comment by Homerus25** [comment]
using the 3.2 branch fixed it. Thanks for your help.
